title: HMPL Blog
author:
  name: ""
  email: ""
description: >
  HMPL - ğŸœ Server-oriented customizable
  templating for JavaScript
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/hmpl-language/hmpl" }
    - { platform: x, user_url: "https://x.com/hmpljs" }
    - { platform: discord, user_url: "https://discord.gg/KFunMep36n" }
    - { platform: rss, user_url: "/feed.xml" }
